server:
  port: 5000
  servlet:
    context-path: /api

spring:
  application:
    name: FoodOrderingAndDeliverySystem

  datasource:
    url: jdbc:mysql://localhost:3306/cs353
    username: cs353
    password: cs353
    initialization-mode: always
    separator: $$

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: fods.log
